/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SGE.ucuenca.capaGUI;

import SGE.ucuenca.capaDatos.Operaciones_OracleBD;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JHON
 */
public class jframe_adminUsuarios extends javax.swing.JFrame {

    Operaciones_OracleBD conectarSystem;
    
    public jframe_adminUsuarios(){
        initComponents();
        setLocationRelativeTo(null);
        conectarSystem = new Operaciones_OracleBD();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_rolUsuarioNuevo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_nombreNuevoUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField_contraseñaNuevoUsuario = new javax.swing.JPasswordField();
        jButton_crearUsuario = new javax.swing.JButton();
        jButton_eliminarUsuario = new javax.swing.JButton();
        jButton_modificarUsuario = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton_admin = new javax.swing.JRadioButton();
        jRadioButton_enc = new javax.swing.JRadioButton();
        jRadioButton_cliente = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_listaAsignar = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel_usuarioSelecAsig = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_lsitaRevocar = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jButton_asignarPrivilegios = new javax.swing.JButton();
        jButton_actualizarPrivAsign = new javax.swing.JButton();
        jComboBox_asignarPrivilegio = new javax.swing.JComboBox<>();
        jLabel_usuarioSelecRev = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton_revocarPrivilegios = new javax.swing.JButton();
        jButton_actualizarPrivRev = new javax.swing.JButton();
        jComboBox_revocarPrivilegios = new javax.swing.JComboBox<>();
        jCheckBox_asignar = new javax.swing.JCheckBox();
        jCheckBox_revocar = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_listaPrivilegiosAsignar = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList_listaPrivilegiosRevocar = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList_listaRolesAsig = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList_listaRolesRevo = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList_listaPrivideRol = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jButton_privilegiosObjetos = new javax.swing.JButton();
        jButton_privilegiosObjetos1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestionar Usuarios"));

        jLabel2.setText("Nombre de usuario:");

        jLabel3.setText("Contraseña usuario:");

        jButton_crearUsuario.setText("Crear");
        jButton_crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_crearUsuarioActionPerformed(evt);
            }
        });

        jButton_eliminarUsuario.setText("Eliminar");
        jButton_eliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarUsuarioActionPerformed(evt);
            }
        });

        jButton_modificarUsuario.setText("Modificar Clave");
        jButton_modificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modificarUsuarioActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Rol de Nuevo Usuario:");

        buttonGroup_rolUsuarioNuevo.add(jRadioButton_admin);
        jRadioButton_admin.setSelected(true);
        jRadioButton_admin.setText("Administrador");
        jRadioButton_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton_adminMouseClicked(evt);
            }
        });

        buttonGroup_rolUsuarioNuevo.add(jRadioButton_enc);
        jRadioButton_enc.setText("Encuestador");
        jRadioButton_enc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton_encMouseClicked(evt);
            }
        });

        buttonGroup_rolUsuarioNuevo.add(jRadioButton_cliente);
        jRadioButton_cliente.setText("Cliente");
        jRadioButton_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton_clienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_admin)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_enc)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_cliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jRadioButton_admin)
                .addComponent(jRadioButton_enc)
                .addComponent(jRadioButton_cliente))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPasswordField_contraseñaNuevoUsuario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_nombreNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_crearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_eliminarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_modificarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_crearUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_eliminarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_modificarUsuario)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_nombreNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField_contraseñaNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion de Permisos"));

        jList_listaAsignar.setEnabled(false);
        jScrollPane1.setViewportView(jList_listaAsignar);

        jLabel4.setText("Usuario seleccionado:");

        jLabel_usuarioSelecAsig.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jList_lsitaRevocar.setEnabled(false);
        jScrollPane2.setViewportView(jList_lsitaRevocar);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_asignarPrivilegios.setText("Asignar Privilegio");
        jButton_asignarPrivilegios.setEnabled(false);
        jButton_asignarPrivilegios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_asignarPrivilegiosActionPerformed(evt);
            }
        });

        jButton_actualizarPrivAsign.setText("Actualizar Privilegios");
        jButton_actualizarPrivAsign.setEnabled(false);
        jButton_actualizarPrivAsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarPrivAsignActionPerformed(evt);
            }
        });

        jComboBox_asignarPrivilegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Crear usuarios", "Eliminar usuarios", "Modificar usuarios", "Crear vistas" }));
        jComboBox_asignarPrivilegio.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox_asignarPrivilegio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_actualizarPrivAsign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_asignarPrivilegios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_asignarPrivilegios)
                    .addComponent(jComboBox_asignarPrivilegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_actualizarPrivAsign)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_usuarioSelecRev.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Usuario seleccionado:");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_revocarPrivilegios.setText("Revocar Privilegio");
        jButton_revocarPrivilegios.setEnabled(false);
        jButton_revocarPrivilegios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_revocarPrivilegiosActionPerformed(evt);
            }
        });

        jButton_actualizarPrivRev.setText("Actualizar Privilegios");
        jButton_actualizarPrivRev.setEnabled(false);
        jButton_actualizarPrivRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarPrivRevActionPerformed(evt);
            }
        });

        jComboBox_revocarPrivilegios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Crear usuarios", "Eliminar usuarios", "Modificar usuarios", "Crear vistas" }));
        jComboBox_revocarPrivilegios.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox_revocarPrivilegios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_actualizarPrivRev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_revocarPrivilegios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_revocarPrivilegios)
                    .addComponent(jComboBox_revocarPrivilegios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_actualizarPrivRev)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jCheckBox_asignar.setText("Asignar Privilegios");
        jCheckBox_asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_asignarActionPerformed(evt);
            }
        });

        jCheckBox_revocar.setText("Revocar Privilegios");
        jCheckBox_revocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_revocarActionPerformed(evt);
            }
        });

        jList_listaPrivilegiosAsignar.setEnabled(false);
        jScrollPane3.setViewportView(jList_listaPrivilegiosAsignar);

        jList_listaPrivilegiosRevocar.setEnabled(false);
        jScrollPane4.setViewportView(jList_listaPrivilegiosRevocar);

        jLabel10.setText("Privilegios de usuario");

        jLabel11.setText("Privilegios de usuario");

        jList_listaRolesAsig.setEnabled(false);
        jScrollPane5.setViewportView(jList_listaRolesAsig);

        jList_listaRolesRevo.setEnabled(false);
        jScrollPane6.setViewportView(jList_listaRolesRevo);

        jLabel12.setText("Roles Asigandos");

        jLabel13.setText("Roles Asignados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(jCheckBox_asignar)
                    .addComponent(jCheckBox_revocar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel_usuarioSelecAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel_usuarioSelecRev, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_usuarioSelecAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_usuarioSelecRev, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox_asignar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jCheckBox_revocar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton2.setText("Actualizar Usuarios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jList_listaPrivideRol.setEnabled(false);
        jScrollPane7.setViewportView(jList_listaPrivideRol);

        jLabel14.setText("Privilegios de Objetos:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton_privilegiosObjetos.setText("Privilegios a Objetos");
        jButton_privilegiosObjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_privilegiosObjetosActionPerformed(evt);
            }
        });

        jButton_privilegiosObjetos1.setText("Gestor de Roles");
        jButton_privilegiosObjetos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_privilegiosObjetos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_privilegiosObjetos))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_privilegiosObjetos1))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton_privilegiosObjetos)
                    .addComponent(jButton_privilegiosObjetos1))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_crearUsuarioActionPerformed
        
        char[] var = jPasswordField_contraseñaNuevoUsuario.getPassword();
        String getPaswordString = new String(var);
        
        if (jRadioButton_admin.isSelected()) {
            if (conectarSystem.crearUsuariosSQL(jTextField_nombreNuevoUsuario.getText(), getPaswordString, 0)) {
                int result = JOptionPane.showConfirmDialog(null, "MENSAJE: \n\tNuevo Administrador Creado", "Aviso!", JOptionPane.OK_CANCEL_OPTION);
            }
        }
        if (jRadioButton_enc.isSelected()) {
            if (conectarSystem.crearUsuariosSQL(jTextField_nombreNuevoUsuario.getText(), getPaswordString, 1)) {
                int result = JOptionPane.showConfirmDialog(null, "MENSAJE: \n\tNuevo Encuestador Creado", "Aviso!", JOptionPane.OK_CANCEL_OPTION);
            }
        }
        
        if (jRadioButton_cliente.isSelected()) {
            if (conectarSystem.crearUsuariosSQL(jTextField_nombreNuevoUsuario.getText(), getPaswordString, 2)) {
                int result = JOptionPane.showConfirmDialog(null, "MENSAJE: \n\tNuevo Cliente Creado", "Aviso!", JOptionPane.OK_CANCEL_OPTION);
            }
        }
        
        
        
        jPasswordField_contraseñaNuevoUsuario.setText("");
        jTextField_nombreNuevoUsuario.setText("");
        
    }//GEN-LAST:event_jButton_crearUsuarioActionPerformed

    private void jButton_eliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarUsuarioActionPerformed
        
        if (conectarSystem.eliminarUsuariosSQL(jTextField_nombreNuevoUsuario.getText())) {
            int result = JOptionPane.showConfirmDialog(null, "MENSAJE: \n\tUsuario Eliminado", "Aviso!", JOptionPane.OK_CANCEL_OPTION);
        }
        
    }//GEN-LAST:event_jButton_eliminarUsuarioActionPerformed

    private void jCheckBox_asignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_asignarActionPerformed
        // TODO add your handling code here:
        if(jCheckBox_asignar.isSelected()== true){
            jButton_asignarPrivilegios.setEnabled(true);
            jButton_actualizarPrivAsign.setEnabled(true);
            jList_listaAsignar.setEnabled(true);
            jList_listaPrivilegiosAsignar.setEnabled(true);
            jComboBox_asignarPrivilegio.setEnabled(true);
        } else {
            jButton_asignarPrivilegios.setEnabled(false);
            jButton_actualizarPrivAsign.setEnabled(false);
            jList_listaAsignar.setEnabled(false);
            jList_listaPrivilegiosAsignar.setEnabled(false);
            jComboBox_asignarPrivilegio.setEnabled(false);
        }
        
    }//GEN-LAST:event_jCheckBox_asignarActionPerformed

    private void jCheckBox_revocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_revocarActionPerformed
        // TODO add your handling code here:
        if(jCheckBox_revocar.isSelected() == true){
            jButton_revocarPrivilegios.setEnabled(true);
            jButton_actualizarPrivRev.setEnabled(true);
            jList_lsitaRevocar.setEnabled(true);
            jList_listaPrivilegiosRevocar.setEnabled(true);
            jComboBox_revocarPrivilegios.setEnabled(true);
        } else {
            jButton_revocarPrivilegios.setEnabled(false);
            jButton_actualizarPrivRev.setEnabled(false);
            jList_lsitaRevocar.setEnabled(false);
            jList_listaPrivilegiosRevocar.setEnabled(false);
            jComboBox_revocarPrivilegios.setEnabled(false);
        }
        
    }//GEN-LAST:event_jCheckBox_revocarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        DefaultListModel modeloListado = new DefaultListModel();
        List<String> aux_lista = conectarSystem.agregarUsuariosJlist();
        Iterator iterador = aux_lista.iterator();
        
        while (iterador.hasNext()) {
            modeloListado.addElement(iterador.next());
        }
        jList_listaAsignar.setModel(modeloListado);
        jList_lsitaRevocar.setModel(modeloListado);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_asignarPrivilegiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_asignarPrivilegiosActionPerformed

        String opcion = (String)jComboBox_asignarPrivilegio.getSelectedItem();
        String usuarioSeleccionado = jList_listaAsignar.getSelectedValue();
        String cadena = "";
        if(opcion.equalsIgnoreCase("Crear vistas")){
            //Seleccionar, Crear usuarios, Eliminar usuarios, Modificar usuarios, Crear vistas
            cadena = "CREATE VIEW";
        }
        if(opcion.equalsIgnoreCase("Eliminar usuarios")){
            cadena = "DROP USER";
        }
        if(opcion.equalsIgnoreCase("Crear usuarios")){
            cadena = "CREATE USER";
        }
        if(opcion.equalsIgnoreCase("Modificar usuarios")){
            cadena = "ALTER USER";
        }
        
        conectarSystem.agregarPrivilegios(cadena, usuarioSeleccionado);

    }//GEN-LAST:event_jButton_asignarPrivilegiosActionPerformed

    private void jButton_revocarPrivilegiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_revocarPrivilegiosActionPerformed
        
        String opcion = (String)jComboBox_revocarPrivilegios.getSelectedItem();
        String usuarioSeleccionado = jList_lsitaRevocar.getSelectedValue();
        String cadena = "";
        if(opcion.equalsIgnoreCase("Crear vistas")){
            //Seleccionar, Crear usuarios, Eliminar usuarios, Modificar usuarios, Crear vistas
            cadena = "CREATE VIEW";
        }
        if(opcion.equalsIgnoreCase("Eliminar usuarios")){
            cadena = "DROP USER";
        }
        if(opcion.equalsIgnoreCase("Crear usuarios")){
            cadena = "CREATE USER";
        }
        if(opcion.equalsIgnoreCase("Modificar usuarios")){
            cadena = "ALTER USER";
        }
        
        conectarSystem.quitarPrivilegios(cadena, usuarioSeleccionado);
        
    }//GEN-LAST:event_jButton_revocarPrivilegiosActionPerformed

    private void jButton_actualizarPrivAsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarPrivAsignActionPerformed
        
        String usuarioSeleccionado = jList_listaAsignar.getSelectedValue();
        jLabel_usuarioSelecAsig.setText(usuarioSeleccionado);
        
        DefaultListModel modeloListado = new DefaultListModel();
        List<String> aux_lista = conectarSystem.agregarPrivilegiosJlist("'"+usuarioSeleccionado+"'");
        Iterator iterador = aux_lista.iterator();
        
        while (iterador.hasNext()) {
            modeloListado.addElement(iterador.next());
        }
        jList_listaPrivilegiosAsignar.setModel(modeloListado);
        jList_listaPrivilegiosRevocar.setModel(modeloListado);
        
        //Llenar el jList de Roles de Cada usuario
        modeloListado = new DefaultListModel();
        aux_lista = conectarSystem.agregarRolesUsuarioSelect("'"+usuarioSeleccionado+"'");
        iterador = aux_lista.iterator();
        
        while (iterador.hasNext()) {
            modeloListado.addElement(iterador.next());
        }
        jList_listaRolesAsig.setModel(modeloListado);
        
    }//GEN-LAST:event_jButton_actualizarPrivAsignActionPerformed

    private void jButton_actualizarPrivRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarPrivRevActionPerformed
        
        String usuarioSeleccionado = jList_lsitaRevocar.getSelectedValue();
        jLabel_usuarioSelecRev.setText(usuarioSeleccionado);
        
        DefaultListModel modeloListado = new DefaultListModel();
        List<String> aux_lista = conectarSystem.agregarPrivilegiosJlist("'"+usuarioSeleccionado+"'");
        Iterator iterador = aux_lista.iterator();
        
        while (iterador.hasNext()) {
            modeloListado.addElement(iterador.next());
        }
        jList_listaPrivilegiosAsignar.setModel(modeloListado);
        jList_listaPrivilegiosRevocar.setModel(modeloListado);
        
        //Llenar el jList de Roles de Cada usuario
        modeloListado = new DefaultListModel();
        aux_lista = conectarSystem.agregarRolesUsuarioSelect("'"+usuarioSeleccionado+"'");
        iterador = aux_lista.iterator();
        
        while (iterador.hasNext()) {
            modeloListado.addElement(iterador.next());
        }
        jList_listaRolesRevo.setModel(modeloListado);
        
    }//GEN-LAST:event_jButton_actualizarPrivRevActionPerformed

    private void jButton_modificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modificarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_modificarUsuarioActionPerformed

    private void jRadioButton_encMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton_encMouseClicked
        
        DefaultListModel modeloListado = new DefaultListModel();
        //Cuando se tenga para Modificar el LIST en VENTANA Admin_ROLES_IBJECTS
        List<String> aux_lista = new ArrayList<>();
        aux_lista.add("INSERT - USUARIO");
        aux_lista.add("UPDATE - USUARIO");
        aux_lista.add("DELETE - USUARIO");
        aux_lista.add("SELECT - USUARIO");
        aux_lista.add("INSERT - TIPO_ENCUESTA");
        aux_lista.add("UPDATE - TIPO_ENCUESTA");
        aux_lista.add("DELETE - TIPO_ENCUESTA");
        aux_lista.add("SELECT - TIPO_ENCUESTA");
        aux_lista.add("INSERT - ENCUESTA");
        aux_lista.add("UPDATE - ENCUESTA");
        aux_lista.add("DELETE - ENCUESTA");
        aux_lista.add("SELECT - ENCUESTA");
        aux_lista.add("INSERT - PREGUNTA");
        aux_lista.add("UPDATE - PREGUNTA");
        aux_lista.add("DELETE - PREGUNTA");
        aux_lista.add("SELECT - PREGUNTA");
        aux_lista.add("INSERT - P_OPMULTIPLE");
        aux_lista.add("UPDATE - P_OPMULTIPLE");
        aux_lista.add("DELETE - P_OPMULTIPLE");
        aux_lista.add("SELECT - P_OPMULTIPLE");
        
        Iterator iterador = aux_lista.iterator();
        while (iterador.hasNext()) {
            modeloListado.addElement(iterador.next());
        }
        jList_listaPrivideRol.setModel(modeloListado);
        
//        DefaultListModel modeloListado = new DefaultListModel();
//        List<String> aux_lista = conectarSystem.agregarRolesJlist("'ROL_ENCUESTADOR'");
//        Iterator iterador = aux_lista.iterator();
//
//        while (iterador.hasNext()) {
//            modeloListado.addElement(iterador.next());
//        }
//        jList_listaPrivideRol.setModel(modeloListado);
        
    }//GEN-LAST:event_jRadioButton_encMouseClicked

    private void jRadioButton_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton_adminMouseClicked
        
        DefaultListModel modeloListado = new DefaultListModel();
        //Cuando se tenga para Modificar el LIST en VENTANA Admin_ROLES_IBJECTS
        List<String> aux_lista = new ArrayList<>();
        aux_lista.add("TODOS LOS PRIVILEGIOS");
        
        Iterator iterador = aux_lista.iterator();
        while (iterador.hasNext()) {
            modeloListado.addElement(iterador.next());
        }
        jList_listaPrivideRol.setModel(modeloListado);
        
        
//        DefaultListModel modeloListado = new DefaultListModel();
//        List<String> aux_lista = conectarSystem.agregarRolesJlist("'ROL_ADMINISTRADOR'");
//        Iterator iterador = aux_lista.iterator();
//
//        while (iterador.hasNext()) {
//            modeloListado.addElement(iterador.next());
//        }
//        jList_listaPrivideRol.setModel(modeloListado);
        
    }//GEN-LAST:event_jRadioButton_adminMouseClicked

    private void jButton_privilegiosObjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_privilegiosObjetosActionPerformed
        
        
    }//GEN-LAST:event_jButton_privilegiosObjetosActionPerformed

    private void jButton_privilegiosObjetos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_privilegiosObjetos1ActionPerformed
        
        
    }//GEN-LAST:event_jButton_privilegiosObjetos1ActionPerformed

    private void jRadioButton_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton_clienteMouseClicked
        
        DefaultListModel modeloListado = new DefaultListModel();
        //Cuando se tenga para Modificar el LIST en VENTANA Admin_ROLES_IBJECTS
        List<String> aux_lista = new ArrayList<>();
        aux_lista.add("INSERT - RESPUESTA_TEXTO");
        aux_lista.add("UPDATE - RESPUESTA_TEXTO");
        aux_lista.add("DELETE - RESPUESTA_TEXTO");
        aux_lista.add("SELECT - RESPUESTA_TEXTO");
        aux_lista.add("INSERT - RESPUESTA_OPCION");
        aux_lista.add("UPDATE - RESPUESTA_OPCION");
        aux_lista.add("DELETE - RESPUESTA_OPCION");
        aux_lista.add("SELECT - RESPUESTA_OPCION");
        
        Iterator iterador = aux_lista.iterator();
        while (iterador.hasNext()) {
            modeloListado.addElement(iterador.next());
        }
        jList_listaPrivideRol.setModel(modeloListado);
        
//        DefaultListModel modeloListado = new DefaultListModel();
//        List<String> aux_lista = conectarSystem.agregarRolesJlist("'ROL_CLIENTE'");
//        Iterator iterador = aux_lista.iterator();
//
//        while (iterador.hasNext()) {
//            modeloListado.addElement(iterador.next());
//        }
//        jList_listaPrivideRol.setModel(modeloListado);
        
    }//GEN-LAST:event_jRadioButton_clienteMouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe_adminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe_adminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe_adminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe_adminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe_adminUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_rolUsuarioNuevo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_actualizarPrivAsign;
    private javax.swing.JButton jButton_actualizarPrivRev;
    private javax.swing.JButton jButton_asignarPrivilegios;
    private javax.swing.JButton jButton_crearUsuario;
    private javax.swing.JButton jButton_eliminarUsuario;
    private javax.swing.JButton jButton_modificarUsuario;
    private javax.swing.JButton jButton_privilegiosObjetos;
    private javax.swing.JButton jButton_privilegiosObjetos1;
    private javax.swing.JButton jButton_revocarPrivilegios;
    private javax.swing.JCheckBox jCheckBox_asignar;
    private javax.swing.JCheckBox jCheckBox_revocar;
    private javax.swing.JComboBox<String> jComboBox_asignarPrivilegio;
    private javax.swing.JComboBox<String> jComboBox_revocarPrivilegios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_usuarioSelecAsig;
    private javax.swing.JLabel jLabel_usuarioSelecRev;
    public static javax.swing.JList<String> jList_listaAsignar;
    public static javax.swing.JList<String> jList_listaPrivideRol;
    public static javax.swing.JList<String> jList_listaPrivilegiosAsignar;
    public static javax.swing.JList<String> jList_listaPrivilegiosRevocar;
    public static javax.swing.JList<String> jList_listaRolesAsig;
    public static javax.swing.JList<String> jList_listaRolesRevo;
    public static javax.swing.JList<String> jList_lsitaRevocar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField_contraseñaNuevoUsuario;
    private javax.swing.JRadioButton jRadioButton_admin;
    private javax.swing.JRadioButton jRadioButton_cliente;
    private javax.swing.JRadioButton jRadioButton_enc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextField_nombreNuevoUsuario;
    // End of variables declaration//GEN-END:variables
}
