/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SGE.ucuenca.capaGUI;

import SGE.ucuenca.capLogica.ClaseValidacion;
import SGE.ucuenca.capLogica.Respuesta_Opcion;
import SGE.ucuenca.capLogica.Respuesta_Texto;
import SGE.ucuenca.capLogica.Usuario;
import SGE.ucuenca.capaDatos.Operaciones_OracleBD;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhon
 */
public class jframe_RealizarEncuesta extends javax.swing.JFrame {

    /**
     * Creates new form jframe_RealizarEncuesta
     */
    Operaciones_OracleBD datosRecuperados = new Operaciones_OracleBD();
    public static List<String> camposEnJTable = new ArrayList<String>();
    //Variables de RESPUESTA OPCION
    public int intCodEncuesta = 0;
    public int intCodPregunta = 0;
    public int intCodOpcionPregunta = 0;
    
    public jframe_RealizarEncuesta() {
        initComponents();
        setLocationRelativeTo(null);
        
        //Coneccion
        Operaciones_OracleBD objConn = new Operaciones_OracleBD();
        objConn.cn = objConn.con.Conectar("Encuesta_db","12345");    //Ingresar con los datos de INICIO SESION;
//        objConn.Conectar(jTextField_usuario.getText(), getPasword);
        
        //Este TRY hace que quite el COMMIT AUTOMATICO
        try {
            objConn.cn.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(jframe_STARTEncuesta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTextField_nombre_usuario.setEnabled(false);
        jTextField_direccion_usuario.setEnabled(false);
        jTextField_telefono_usuario.setEnabled(false);
        jTextField_correo_usuario.setEnabled(false);
        jButton_comenzarEncuesta.setEnabled(false);
        jTextField_responderTexto.setEnabled(false);
        jButton_responderTexto.setEnabled(false);
        jButton_responderOpcion.setEnabled(false);
        jButton_siguienteOpcion.setEnabled(false);
        jButton_terminarEncuesta.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_nombre_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_direccion_usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_cod_usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_telefono_usuario = new javax.swing.JTextField();
        jButton_ingresarEncuesta = new javax.swing.JButton();
        jButton_buscarUsuario = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField_correo_usuario = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel_seccionOpciones = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton_responderOpcion = new javax.swing.JButton();
        jButton_siguienteOpcion = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel_seccionTexto = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_responderTexto = new javax.swing.JTextField();
        jButton_responderTexto = new javax.swing.JButton();
        jButton_terminarEncuesta = new javax.swing.JButton();
        jButton_SALIR = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton_comenzarEncuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Usuario"));

        jLabel1.setText("Nombres:");

        jTextField_nombre_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombre_usuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Direccion:");

        jLabel3.setText("Cedula");

        jLabel4.setText("Telefono:");

        jButton_ingresarEncuesta.setText("Iniciar");
        jButton_ingresarEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ingresarEncuestaActionPerformed(evt);
            }
        });

        jButton_buscarUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_buscarUsuario.setText("Buscar");
        jButton_buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarUsuarioActionPerformed(evt);
            }
        });

        jLabel12.setText("Correo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_ingresarEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(0, 3, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(24, 24, 24)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_correo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextField_cod_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_buscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextField_nombre_usuario)
                                .addComponent(jTextField_direccion_usuario)
                                .addComponent(jTextField_telefono_usuario)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscarUsuario)
                    .addComponent(jTextField_cod_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField_direccion_usuario)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField_telefono_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextField_correo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ingresarEncuesta))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel_seccionOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Seccion Opciones"));

        jTable4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jButton_responderOpcion.setText("Responder");
        jButton_responderOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_responderOpcionActionPerformed(evt);
            }
        });

        jButton_siguienteOpcion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_siguienteOpcion.setText("Siguiente");
        jButton_siguienteOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_siguienteOpcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_seccionOpcionesLayout = new javax.swing.GroupLayout(jPanel_seccionOpciones);
        jPanel_seccionOpciones.setLayout(jPanel_seccionOpcionesLayout);
        jPanel_seccionOpcionesLayout.setHorizontalGroup(
            jPanel_seccionOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_seccionOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_seccionOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_seccionOpcionesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_responderOpcion)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_siguienteOpcion)))
                .addContainerGap())
        );
        jPanel_seccionOpcionesLayout.setVerticalGroup(
            jPanel_seccionOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_seccionOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_seccionOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_responderOpcion)
                    .addComponent(jButton_siguienteOpcion))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Seccion Pregunta"));

        jTable5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_seccionTexto.setBorder(javax.swing.BorderFactory.createTitledBorder("Seccion Texto"));

        jLabel5.setText("Respuesta:");

        jButton_responderTexto.setText("Responder");
        jButton_responderTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_responderTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_seccionTextoLayout = new javax.swing.GroupLayout(jPanel_seccionTexto);
        jPanel_seccionTexto.setLayout(jPanel_seccionTextoLayout);
        jPanel_seccionTextoLayout.setHorizontalGroup(
            jPanel_seccionTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_seccionTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_seccionTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_responderTexto)
                    .addComponent(jTextField_responderTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel_seccionTextoLayout.setVerticalGroup(
            jPanel_seccionTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_seccionTextoLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel_seccionTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_responderTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_responderTexto)
                .addContainerGap())
        );

        jButton_terminarEncuesta.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton_terminarEncuesta.setText("TEMINAR ENCUESTA");
        jButton_terminarEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_terminarEncuestaActionPerformed(evt);
            }
        });

        jButton_SALIR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_SALIR.setText("SALIR");
        jButton_SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SALIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel_seccionOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton_terminarEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_SALIR))
                            .addComponent(jPanel_seccionTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_seccionOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel_seccionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_terminarEncuesta)
                            .addComponent(jButton_SALIR))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jButton_comenzarEncuesta.setText("Comenzar Encuesta");
        jButton_comenzarEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_comenzarEncuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_comenzarEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jButton_comenzarEncuesta)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ingresarEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ingresarEncuestaActionPerformed
        
        //Condicion para 
        
        Object objUsuario = new Usuario(
                ClaseValidacion.getNumero(jTextField_cod_usuario.getText()),
                jTextField_nombre_usuario.getText(),
                jTextField_direccion_usuario.getText(),
                jTextField_telefono_usuario.getText(),
                jTextField_correo_usuario.getText());
        try {
            //Enviar los datos a Capa de Datos - Objeto
            
            if (datosRecuperados.insertarRegistros(objUsuario)) {
                //Mostrar Ventana Emergente
                int result = JOptionPane.showConfirmDialog(null, "MENSAJE: \n\nUsuario Ingresado", "Aviso!", JOptionPane.OK_CANCEL_OPTION);
                activarIniciodeEncuesta();
            } else {
                int result = JOptionPane.showConfirmDialog(null, "MENSAJE: \n\nUsuario existente", "Aviso!", JOptionPane.OK_CANCEL_OPTION);
                activarIniciodeEncuesta();
            }
            
        } catch (ParseException ex) {
            System.out.println("ERROR: "+ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton_ingresarEncuestaActionPerformed

    private void jButton_responderOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_responderOpcionActionPerformed
        
        System.out.println("==============================================");
        System.out.println("RESPUESTA Encuesta: "+ intCodEncuesta);
        System.out.println("RESPUESTA Pregunta: "+ intCodPregunta);
        System.out.println("RESPUESTA Opcion:"+ intCodOpcionPregunta);
        System.out.println("USUARIO: "+ jTextField_cod_usuario.getText());
        System.out.println("RESPUESTA OPCION: x");
        System.out.println("==============================================");
        
        //Instanciar la Clase
        Respuesta_Opcion objRespOpcion = new Respuesta_Opcion(
                intCodEncuesta, 
                intCodPregunta,
                intCodOpcionPregunta,
                ClaseValidacion.getNumero(jTextField_cod_usuario.getText()), 
                "x");
        
        try {
            //Enviar los datos a Capa de Datos - Objeto
            datosRecuperados.insertarRegistros(objRespOpcion);
            
        } catch (ParseException ex) {
            System.out.println("ERROR: "+ex);
        }

        //Eliminar pregunta de Jtable PREGUNTA ============================
        DefaultTableModel modelo = (DefaultTableModel) jTable4.getModel();
        int fila = jTable4.getSelectedRow();
        if (fila >= 0) {
            int[] filasselec = jTable4.getSelectedRows();
            for (int i = 0; i < filasselec.length; i++) {
                modelo.removeRow(filasselec[i]);
            }
        } else {System.out.println("ERROR: ");}
        //Eliminar pregunta de Jtable PREGUNTA ============================
        
        
        
    }//GEN-LAST:event_jButton_responderOpcionActionPerformed

    private void jButton_comenzarEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_comenzarEncuestaActionPerformed
        // TODO add your handling code here:
        jTable3.setEnabled(false);
        jButton_comenzarEncuesta.setEnabled(false);
    }//GEN-LAST:event_jButton_comenzarEncuestaActionPerformed

    private void jButton_responderTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_responderTextoActionPerformed
        // TODO add your handling code here:
        System.out.println("==============================================");
        System.out.println("RESPUESTA Encuesta: "+ intCodEncuesta);
        System.out.println("RESPUESTA Pregunta: "+ intCodPregunta);
        System.out.println("USUARIO: "+ jTextField_cod_usuario.getText());
        System.out.println("RESPUESTA Texto:"+ jTextField_responderTexto.getText());
        System.out.println("==============================================");
        
        //Instanciar la Clase
        Respuesta_Texto objRespTexto = new Respuesta_Texto(
                intCodEncuesta, 
                intCodPregunta, 
                ClaseValidacion.getNumero(jTextField_cod_usuario.getText()), 
                jTextField_responderTexto.getText());
        
        try {
            //Enviar los datos a Capa de Datos - Objeto
            datosRecuperados.insertarRegistros(objRespTexto);
            
        } catch (ParseException ex) {
            System.out.println("ERROR: "+ex);
        }
        
        //Eliminar pregunta de Jtable PREGUNTA ============================
        DefaultTableModel modelo = (DefaultTableModel) jTable5.getModel();
        int fila = jTable5.getSelectedRow();
        if (fila >= 0) {
            int[] filasselec = jTable5.getSelectedRows();
            for (int i = 0; i < filasselec.length; i++) {
                modelo.removeRow(filasselec[i]);
            }
        } else {System.out.println("ERROR: ");}
        //Eliminar pregunta de Jtable PREGUNTA ============================
        
        //Validar si esta Vacio el Jtable de PREGUNTA ===================
        if (this.jTable5.getRowCount() != 0 && this.jTable5.getSelectedRow() != 0) { // Condicion VACIO
        } else {
            jButton_terminarEncuesta.setEnabled(true);
            jTextField_responderTexto.setEnabled(false);
            jButton_responderTexto.setEnabled(false);
            jButton_responderOpcion.setEnabled(false);
            jButton_siguienteOpcion.setEnabled(false);
            JOptionPane.showMessageDialog(null, "AVISO:\n\nPREGUNTAS TERMINADAS..!!");
        }
        jTextField_responderTexto.setEnabled(false);
        jButton_responderTexto.setEnabled(false);
        
        
    }//GEN-LAST:event_jButton_responderTextoActionPerformed

    private void jButton_terminarEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_terminarEncuestaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "AVISO:\n\nENCUESTA GUARDADA, GRACIAS..!!");
        
        //Commit
        try {
            // TODO add your handling code here:
            datosRecuperados.startCommitRollback(true);
        } catch (SQLException ex) {
            System.out.println("ERROR: "+ ex);
        }
    }//GEN-LAST:event_jButton_terminarEncuestaActionPerformed

    private void jButton_siguienteOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_siguienteOpcionActionPerformed
        // TODO add your handling code here:
        
        //Insertar las demas RESPUESTAS DE OPCION
        
        //Instanciar la Clase
        //  Lista de OBJETOS y las recorro para Ingresar
        
        
        
        //Eliminar pregunta de Jtable PREGUNTA ============================
        DefaultTableModel modelo = (DefaultTableModel) jTable5.getModel();
        int fila = jTable5.getSelectedRow();
        if (fila >= 0) {
            int[] filasselec = jTable5.getSelectedRows();
            for (int i = 0; i < filasselec.length; i++) {
                modelo.removeRow(filasselec[i]);
            }
        } else {System.out.println("ERROR: ");}
        //Eliminar pregunta de Jtable PREGUNTA ============================
        
        //Validar si esta Vacio el Jtable de PREGUNTA ===================
        if (this.jTable5.getRowCount() != 0 && this.jTable5.getSelectedRow() != 0) { // Condicion VACIO
        } else {
            jButton_terminarEncuesta.setEnabled(true);
            jTextField_responderTexto.setEnabled(false);
            jButton_responderTexto.setEnabled(false);
            jButton_responderOpcion.setEnabled(false);
            jButton_siguienteOpcion.setEnabled(false);
            JOptionPane.showMessageDialog(null, "AVISO:\n\nPREGUNTAS TERMINADAS..!!");
        }
        
    }//GEN-LAST:event_jButton_siguienteOpcionActionPerformed

    private void jButton_SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SALIRActionPerformed
        // TODO add your handling code here:  
        //Rollback
        try {
            // TODO add your handling code here:
            datosRecuperados.startCommitRollback(false);
        } catch (SQLException ex) {
            System.out.println("ERROR: "+ ex);
        }
        this.dispose();
        
    }//GEN-LAST:event_jButton_SALIRActionPerformed

    private void jButton_buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarUsuarioActionPerformed
        // TODO add your handling code here:
        
        jTextField_nombre_usuario.setEnabled(true);
        jTextField_direccion_usuario.setEnabled(true);
        jTextField_telefono_usuario.setEnabled(true);
        jTextField_correo_usuario.setEnabled(true);
        
    }//GEN-LAST:event_jButton_buscarUsuarioActionPerformed

    private void jTextField_nombre_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombre_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombre_usuarioActionPerformed
    
    //===========================================================================
    //MOSTRAR PREGUNTA
    public void mostrarPregunta(int valorCodEncuesta){
        String ingresoTablaSelec = "PREGUNTA";
        String cadenaCamposAgregados = "COD_PREGUNTA, DESCRIPCION";
        camposEnJTable.add("COD_PREGUNTA");
        camposEnJTable.add("DESCRIPCION");
        
        datosRecuperados.metaDatoTablasJtable();
        
        try {
            //MOSTRAR PREGUNTA
            //Mostrar ANTES de consultar
            datosRecuperados.metaDatoCamposTablaJtable(ingresoTablaSelec);
            System.out.println("\n===============\nSELECT "+cadenaCamposAgregados+" FROM " + ingresoTablaSelec + " WHERE COD_ENCUESTA = " + valorCodEncuesta+"\n===============\n");
            jTable5.setModel(datosRecuperados.consultarRegistrosJTable(cadenaCamposAgregados, ingresoTablaSelec, " WHERE COD_ENCUESTA = " + valorCodEncuesta));
            
            //Seleccionar valores con Mause
            jTable5.addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent e) {
                    int fila = jTable5.rowAtPoint(e.getPoint());
                    int columna = jTable5.columnAtPoint(e.getPoint());
                    if ((fila > -1) && (columna > -1)) {
                        
                        mostrarPreguntaOpciones(valorCodEncuesta,ClaseValidacion.getNumero((String)jTable5.getValueAt(fila, columna)));
                        //Obtener valor de codigo de encuesta
                        intCodPregunta = ClaseValidacion.getNumero((String)jTable5.getValueAt(fila, columna));
//                        System.out.println("VALOR ELEGIDO DE OPCION: "+ intCodEncuesta);
                    }
                }
            });
            
            
        } catch (SQLException ex) {
            System.out.println("ERROR: "+ex);
        }
        camposEnJTable.clear();
        
    }
    
    //MOSTRAR OPCIONES
    public void mostrarPreguntaOpciones(int valorCodEncuesta, int valorCodPregunta){
        String ingresoTablaSelec = "P_OPMULTIPLE";
        String cadenaCamposAgregados = "COD_OPC_MULTIPLE, DESC_OPCION";
        camposEnJTable.add("COD_OPC_MULTIPLE");
        camposEnJTable.add("DESC_OPCION");
        
        datosRecuperados.metaDatoTablasJtable();
        
        try {
            //MOSTRAR OPCIONES
            //Mostrar ANTES de consultar
            datosRecuperados.metaDatoCamposTablaJtable(ingresoTablaSelec);
            System.out.println("\n===============\nSELECT "+cadenaCamposAgregados+" FROM " + ingresoTablaSelec + " WHERE COD_ENCUESTA = " + valorCodEncuesta + " AND COD_PREGUNTA = " +valorCodPregunta+"\n===============\n");
            
            jTable4.setModel(datosRecuperados.consultarRegistrosJTable(cadenaCamposAgregados, ingresoTablaSelec, " WHERE COD_ENCUESTA = " + valorCodEncuesta + " AND COD_PREGUNTA = " +valorCodPregunta));
            //Seleccionar valores con Mause - Envia el valor a TERMINAR ENCUESTA
            jTable4.addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent e) {
                    int fila = jTable4.rowAtPoint(e.getPoint());
                    int columna = jTable4.columnAtPoint(e.getPoint());
                    if ((fila > -1) && (columna > -1)) {
                        
                        //Obtener valor de codigo de pregunta
                        intCodOpcionPregunta = ClaseValidacion.getNumero((String) jTable4.getValueAt(fila, columna));
//                        System.out.println("VALOR ELEGIDO DE OPCION: "+ intCodPregunta);
                    }
                }
            });
            
            
            //Validar si esta Vacio el Jtable de Op Multiple ===================
            if (this.jTable4.getRowCount() != 0 && this.jTable4.getSelectedRow() != 0) { // Condicion VACIO
                jTextField_responderTexto.setEnabled(false);
                jButton_responderTexto.setEnabled(false);
                jButton_responderOpcion.setEnabled(true);
                jButton_siguienteOpcion.setEnabled(true);
            } else {
                jTextField_responderTexto.setEnabled(true);
                jButton_responderTexto.setEnabled(true);
                jButton_responderOpcion.setEnabled(false);
                jButton_siguienteOpcion.setEnabled(false);
            }
            
        } catch (SQLException ex) {
            System.out.println("ERROR: "+ex);
        }
        camposEnJTable.clear();
        
    }
    
    //===========================================================================
    
    //ACTIVAR PARA LLENAR LA ENCUESTA
    public void activarIniciodeEncuesta(){
        //Deshabilirar Botones y Jtexts
        jTextField_cod_usuario.setEnabled(false);
        jTextField_nombre_usuario.setEnabled(false);
        jTextField_direccion_usuario.setEnabled(false);
        jTextField_telefono_usuario.setEnabled(false);
         jTextField_correo_usuario.setEnabled(false);
        jButton_ingresarEncuesta.setEnabled(false);
        
        //Activar JTable de Encuestas
        String ingresoTablaSelec = "ENCUESTA";
        String cadenaCamposAgregados = "COD_ENCUESTA, NOMBRE";
        camposEnJTable.add("COD_ENCUESTA");
        camposEnJTable.add("NOMBRE");
        
        datosRecuperados.metaDatoTablasJtable();
        
        try {
            //MOSTRAR ENCUESTAS
            //Mostrar ANTES de consultar
            datosRecuperados.metaDatoCamposTablaJtable(ingresoTablaSelec);
            System.out.println("\n===============\nSELECT " + cadenaCamposAgregados + " FROM " + ingresoTablaSelec + " " + "" + "\n===============\n");
            jTable3.setModel(datosRecuperados.consultarRegistrosJTable(cadenaCamposAgregados, ingresoTablaSelec, ""));     // ( * , nombre de una tabla , CONDICIONES despues del nombre tabla )

            //Seleccionar valores con Mause
            jTable3.addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent e) {
                    int fila = jTable3.rowAtPoint(e.getPoint());
                    int columna = jTable3.columnAtPoint(e.getPoint());
                    if ((fila > -1) && (columna > -1)) {
                        
                        mostrarPregunta(ClaseValidacion.getNumero((String)jTable3.getValueAt(fila, columna)));
                        intCodEncuesta = ClaseValidacion.getNumero((String)jTable3.getValueAt(fila, columna));
//                        System.out.println("VALOR ELEGIDO DE OPCION: "+ intCodEncuesta);
                    
                    }
                }
            });
            
        } catch (SQLException ex) {
            System.out.println("ERR: "+ex.getMessage());
        }
        camposEnJTable.clear();
        jButton_comenzarEncuesta.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe_RealizarEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe_RealizarEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe_RealizarEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe_RealizarEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe_RealizarEncuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_SALIR;
    private javax.swing.JButton jButton_buscarUsuario;
    private javax.swing.JButton jButton_comenzarEncuesta;
    private javax.swing.JButton jButton_ingresarEncuesta;
    private javax.swing.JButton jButton_responderOpcion;
    private javax.swing.JButton jButton_responderTexto;
    private javax.swing.JButton jButton_siguienteOpcion;
    private javax.swing.JButton jButton_terminarEncuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_seccionOpciones;
    private javax.swing.JPanel jPanel_seccionTexto;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField_cod_usuario;
    private javax.swing.JTextField jTextField_correo_usuario;
    private javax.swing.JTextField jTextField_direccion_usuario;
    private javax.swing.JTextField jTextField_nombre_usuario;
    private javax.swing.JTextField jTextField_responderTexto;
    private javax.swing.JTextField jTextField_telefono_usuario;
    // End of variables declaration//GEN-END:variables
}
